name: nlp_practice
channels:
  - defaults
dependencies:
  - python==3.8.5
  - requests
  - pandas
  - numpy
  - beautifulsoup4
  - lxml
  - jupyter
  - nltk
  - matplotlib
  - pip
  - pip:
    - sklearn
    - gensim
  